// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYyfAvvID5sKpwgnbOYV9ai5JsqCq5zyg',
    appId: '1:540281549849:web:0816e9dce69babad6f2688',
    messagingSenderId: '540281549849',
    projectId: 'fcm4flutter-85234',
    authDomain: 'fcm4flutter-85234.firebaseapp.com',
    storageBucket: 'fcm4flutter-85234.firebasestorage.app',
    measurementId: 'G-F1LB4GMFD8',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6qV81t0NWalSt5B7Yqy8aVYw9MST_yCc',
    appId: '1:540281549849:ios:8e63ca6d2e18043e6f2688',
    messagingSenderId: '540281549849',
    projectId: 'fcm4flutter-85234',
    storageBucket: 'fcm4flutter-85234.firebasestorage.app',
    iosBundleId: 'com.example.exercise6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6qV81t0NWalSt5B7Yqy8aVYw9MST_yCc',
    appId: '1:540281549849:ios:8e63ca6d2e18043e6f2688',
    messagingSenderId: '540281549849',
    projectId: 'fcm4flutter-85234',
    storageBucket: 'fcm4flutter-85234.firebasestorage.app',
    iosBundleId: 'com.example.exercise6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsxrEzgV9TO9GHkd9ix5wYct9vcovtPyQ',
    appId: '1:540281549849:android:e2b39801347749536f2688',
    messagingSenderId: '540281549849',
    projectId: 'fcm4flutter-85234',
    storageBucket: 'fcm4flutter-85234.firebasestorage.app',
  );

}