// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  // TODO (codelab user): Replace with your Firebase credentials

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZnjbiwP7Yot6bcUOmkOWMw5HHyndGzqE',
    appId: '1:566792589403:web:0d241d77d89ef01b39ef7e',
    messagingSenderId: '566792589403',
    projectId: 'huijiadi-info6350-exercise',
    authDomain: 'huijiadi-info6350-exercise.firebaseapp.com',
    storageBucket: 'huijiadi-info6350-exercise.firebasestorage.app',
    measurementId: 'G-SKXM87C44X',
  );

  // Generate this file with credentials with the FlutterFire CLI

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR API KEY',
    appId: 'YOUR APP ID',
    messagingSenderId: '',
    projectId: 'flutterfire-ui-codelab',
    storageBucket: 'flutterfire-ui-codelab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwuzH2EPioXg66ZNigLqtL1pBQlEjLRp8',
    appId: '1:566792589403:ios:a2f2bba33819468b39ef7e',
    messagingSenderId: '566792589403',
    projectId: 'huijiadi-info6350-exercise',
    storageBucket: 'huijiadi-info6350-exercise.firebasestorage.app',
    iosClientId: '566792589403-bqj6ba6pik5nk4csn7jo2f785g2hrqsm.apps.googleusercontent.com',
    iosBundleId: 'com.example.start',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwuzH2EPioXg66ZNigLqtL1pBQlEjLRp8',
    appId: '1:566792589403:ios:a2f2bba33819468b39ef7e',
    messagingSenderId: '566792589403',
    projectId: 'huijiadi-info6350-exercise',
    storageBucket: 'huijiadi-info6350-exercise.firebasestorage.app',
    iosClientId: '566792589403-bqj6ba6pik5nk4csn7jo2f785g2hrqsm.apps.googleusercontent.com',
    iosBundleId: 'com.example.start',
  );

}